---
title: "Facility Analysis"
author: "Patrick Talley"
date: "December 2, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Facility Value 

This uses the distance volume from Julia to create a daily dollar amount for floor space on the facility.

### Set constants 
```{r}
totalArea <- 1884*4124 # Area of the facility
fCost <- 700000 # Assumed yearly cost of the facility
gArea <- 48*48 # Area of a gaylord
```

### Load data and normalize 

Data is normalized so that it is unitless. 

```{r}
## Load data
nochange <- as.matrix(read.table("costNoChange.csv", sep=","))
noNorm <- nochange / sum(nochange) #Normalize


fullchange <- as.matrix(read.table("costFullChange.csv", sep=","))
fullNorm <- fullchange / sum(fullchange)

kingchange <- as.matrix(read.table("costKing.csv", sep=","))
kingnorm <- kingchange / sum(kingchange)
```

### Analysis of facility without any change

For this, we use the normalized facility data, then we set the areas where CRTs are being stored.

```{r}
# TV areas
tvNochangeRow <- c((48*21):(48*29),1:(6*48))
tvNochangeCol <- c((30*48):(62*48))
tvNo1 <- noNorm[(48*21):(48*29),(30*48):(62*48)]
tvNo2 <- noNorm[(1:(6*48)),(30*48):(62*38)]


tvFull1 <- fullNorm[1:(48*2),(30*48):(62*48)]
tvFull2 <- fullNorm[1:(48*16),(10*48):(26*48)]

kingRow1 <- (21*48):(36*48)
kingCol1 <- 1:(29*48)
king1 <- kingnorm[kingRow1,kingCol1]
king2 <- kingnorm[1:(48*2),(30*48):(62*48)]

noChangeCost <- mean(tail(sort(c(tvNo1,tvNo2)),gArea)) * fCost * gArea / 365 

fullCost <- mean(tail(sort(c(tvFull1,tvFull2)),gArea)) * fCost * gArea / 365

kingCost <- mean(tail(sort(c(king1,king2)),gArea)) * fCost * gArea / 365 

sprintf("No facility change: $%.2f /(day gaylord)", noChangeCost)
sprintf("Team change: $%.2f /(day gaylord)", fullCost)
sprintf("King change: $%.2f /(day gaylord)", kingCost)

```

